// Code generated by "stringer -type=PacketError"; DO NOT EDIT.

package packet

import "strconv"

const _PacketError_name = "BUFFER_SIZE_ERRORTYPE_ERRORFLAGS_ERRORREMAIN_LENGTH_ERRORREMAIN_BUFFERR_SIZE_ERROR"

var _PacketError_index = [...]uint8{0, 17, 27, 38, 57, 82}

func (i PacketError) String() string {
	i -= 1
	if i < 0 || i >= PacketError(len(_PacketError_index)-1) {
		return "PacketError(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _PacketError_name[_PacketError_index[i]:_PacketError_index[i+1]]
}
