// Code generated by "stringer -type=Type"; DO NOT EDIT.

package packet

import "strconv"

const _Type_name = "CONNECTCONNACKPUBLISHPUBACKPUBRECPUBRELPUBCOMPSUBSCRIBESUBACKUNSUBSCRIBEUNSUBACKPINGREQPINGRESPDISCONNECT"

var _Type_index = [...]uint8{0, 7, 14, 21, 27, 33, 39, 46, 55, 61, 72, 80, 87, 95, 105}

func (i Type) String() string {
	i -= 1
	if i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
